In [2]:
!pip install torch

In [16]:
import torch

In [18]:
one_d = torch.arange(0, 9)
one_d

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
two_d = one_d.view(3, 3)
two_d

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [20]:
two_d.dim()

2

In [22]:
two_d[1, 2]

tensor(5)

In [25]:
x = torch.arange(18).view(3, 3, 2)
x

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]])