In [2]:
!pip install torch

In [16]:
import torch

In [28]:
mat_a = torch.tensor([0, 3, 5, 5, 5, 2]).view(2, 3)
mat_a

tensor([[0, 3, 5],
        [5, 5, 2]])

In [29]:
mat_b = torch.tensor([3, 4, 3, -2, 4, -2]).view(3, 2)
mat_b

tensor([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])

In [30]:
torch.matmul(mat_a, mat_b)

tensor([[ 29, -16],
        [ 38,   6]])

In [31]:
mat_a @ mat_b

tensor([[ 29, -16],
        [ 38,   6]])